"""alter

Revision ID: 0d5a8dc6429c
Revises: 8e3b08bb83a8
Create Date: 2023-05-14 18:46:09.114228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5a8dc6429c'
down_revision = '8e3b08bb83a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
