"""initial

Revision ID: b7f9ac711ae5
Revises: 94eba7183e46
Create Date: 2023-05-13 17:31:13.567991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f9ac711ae5'
down_revision = '94eba7183e46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
