"""alter1

Revision ID: f4906ce8a285
Revises: 0d5a8dc6429c
Create Date: 2023-05-14 18:49:10.012228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4906ce8a285'
down_revision = '0d5a8dc6429c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('hotel_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'hotel_id')
    # ### end Alembic commands ###
